version: '3.3'
services:

  frontend:
    image: umlilia/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:14.11-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  web:
    image: umlilia/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/etc/nginx/html/static/
      - media_value:/etc/nginx/html/media/
    depends_on:
      - web
    restart: always

volumes:
  static_value:
  media_value:
